# Generated by Django 4.2.1 on 2023-05-27 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='구인중', max_length=10, verbose_name='상태')),
                ('title', models.CharField(max_length=64, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('price', models.CharField(max_length=20, verbose_name='가격')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='등록 시간')),
                ('start_date', models.DateTimeField(verbose_name='시작 시간')),
                ('end_date', models.DateTimeField(verbose_name='종료 시간')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '게시물',
                'verbose_name_plural': '게시물',
                'db_table': 'community_board',
            },
        ),
    ]
